package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.optaplanner.core.api.domain.entity.PlanningEntity
public class Booking implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String id;
	private java.lang.String language;
	private java.lang.String customerId;
	private java.time.LocalDateTime startTime;
	private java.time.LocalDateTime endTime;
	private java.lang.String type;

	@org.optaplanner.core.api.domain.variable.PlanningVariable(valueRangeProviderRefs = {"translatorRange"})
	private com.Translator translator;

	public Booking() {
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.String getLanguage() {
		return this.language;
	}

	public void setLanguage(java.lang.String language) {
		this.language = language;
	}

	public java.lang.String getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(java.lang.String customerId) {
		this.customerId = customerId;
	}

	public java.time.LocalDateTime getStartTime() {
		return this.startTime;
	}

	public void setStartTime(java.time.LocalDateTime startTime) {
		this.startTime = startTime;
	}

	public java.time.LocalDateTime getEndTime() {
		return this.endTime;
	}

	public void setEndTime(java.time.LocalDateTime endTime) {
		this.endTime = endTime;
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public com.Translator getTranslator() {
		return this.translator;
	}

	public void setTranslator(com.Translator translator) {
		this.translator = translator;
	}

	public Booking(java.lang.String id, java.lang.String language,
			java.lang.String customerId, java.time.LocalDateTime startTime,
			java.time.LocalDateTime endTime, java.lang.String type,
			com.Translator translator) {
		this.id = id;
		this.language = language;
		this.customerId = customerId;
		this.startTime = startTime;
		this.endTime = endTime;
		this.type = type;
		this.translator = translator;
	}

}