package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.optaplanner.core.api.domain.solution.PlanningSolution(autoDiscoverMemberType = org.optaplanner.core.api.domain.autodiscover.AutoDiscoverMemberType.FIELD)
@javax.xml.bind.annotation.XmlRootElement
@javax.xml.bind.annotation.XmlAccessorType(javax.xml.bind.annotation.XmlAccessType.FIELD)
public class bookingRoster implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.List<com.Booking> bookings;
	private java.lang.Long id;
	@org.optaplanner.core.api.domain.valuerange.ValueRangeProvider(id = "translatorRange")
	private java.util.List<com.Translator> translators;
	private java.util.List<com.customerDistance> customTranslators;
	@javax.annotation.Generated(value = {"org.optaplanner.workbench.screens.domaineditor.client.widgets.planner.PlannerDataObjectEditor"})
	@javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter(value = org.optaplanner.persistence.jaxb.api.score.buildin.hardmediumsoft.HardMediumSoftScoreJaxbXmlAdapter.class)
	@org.kie.api.definition.type.Label(value = "Generated Planner score field")
	@org.optaplanner.core.api.domain.solution.PlanningScore
	private org.optaplanner.core.api.score.buildin.hardmediumsoft.HardMediumSoftScore score;

	public bookingRoster() {
	}

	public java.util.List<com.Booking> getBookings() {
		return this.bookings;
	}

	public void setBookings(java.util.List<com.Booking> bookings) {
		this.bookings = bookings;
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.util.List<com.Translator> getTranslators() {
		return this.translators;
	}

	public void setTranslators(java.util.List<com.Translator> translators) {
		this.translators = translators;
	}

	public java.util.List<com.customerDistance> getCustomTranslators() {
		return this.customTranslators;
	}

	public void setCustomTranslators(
			java.util.List<com.customerDistance> customTranslators) {
		this.customTranslators = customTranslators;
	}

	public org.optaplanner.core.api.score.buildin.hardmediumsoft.HardMediumSoftScore getScore() {
		return this.score;
	}

	public void setScore(
			org.optaplanner.core.api.score.buildin.hardmediumsoft.HardMediumSoftScore score) {
		this.score = score;
	}

	public bookingRoster(
			java.util.List<com.Booking> bookings,
			java.lang.Long id,
			java.util.List<com.Translator> translators,
			java.util.List<com.customerDistance> customTranslators,
			org.optaplanner.core.api.score.buildin.hardmediumsoft.HardMediumSoftScore score) {
		this.bookings = bookings;
		this.id = id;
		this.translators = translators;
		this.customTranslators = customTranslators;
		this.score = score;
	}

}