package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class customerDistance implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private String booking_id;

	private String translator_id;

	private int temp_travel_time_public;

	private int temp_travel_time_car;

	private int temp_travel_distance_public;

	private int temp_travel_distance_car;

	public customerDistance() {
	}

	public java.lang.String getBooking_id() {
		return this.booking_id;
	}

	public void setBooking_id(java.lang.String booking_id) {
		this.booking_id = booking_id;
	}

	public java.lang.String getTranslator_id() {
		return this.translator_id;
	}

	public void setTranslator_id(java.lang.String translator_id) {
		this.translator_id = translator_id;
	}

	public int getTemp_travel_time_public() {
		return this.temp_travel_time_public;
	}

	public void setTemp_travel_time_public(int temp_travel_time_public) {
		this.temp_travel_time_public = temp_travel_time_public;
	}

	public int getTemp_travel_time_car() {
		return this.temp_travel_time_car;
	}

	public void setTemp_travel_time_car(int temp_travel_time_car) {
		this.temp_travel_time_car = temp_travel_time_car;
	}

	public int getTemp_travel_distance_public() {
		return this.temp_travel_distance_public;
	}

	public void setTemp_travel_distance_public(int temp_travel_distance_public) {
		this.temp_travel_distance_public = temp_travel_distance_public;
	}

	public int getTemp_travel_distance_car() {
		return this.temp_travel_distance_car;
	}

	public void setTemp_travel_distance_car(int temp_travel_distance_car) {
		this.temp_travel_distance_car = temp_travel_distance_car;
	}

	public customerDistance(java.lang.String booking_id,
			java.lang.String translator_id, int temp_travel_time_public,
			int temp_travel_time_car, int temp_travel_distance_public,
			int temp_travel_distance_car) {
		this.booking_id = booking_id;
		this.translator_id = translator_id;
		this.temp_travel_time_public = temp_travel_time_public;
		this.temp_travel_time_car = temp_travel_time_car;
		this.temp_travel_distance_public = temp_travel_distance_public;
		this.temp_travel_distance_car = temp_travel_distance_car;
	}

}