package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Translator implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String id;
	private java.lang.String level;
	private java.lang.String ADRESS;
	private java.lang.String PADR;
	private java.lang.String language;

	private int feedBack;

	public Translator() {
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.String getLevel() {
		return this.level;
	}

	public void setLevel(java.lang.String level) {
		this.level = level;
	}

	public java.lang.String getADRESS() {
		return this.ADRESS;
	}

	public void setADRESS(java.lang.String ADRESS) {
		this.ADRESS = ADRESS;
	}

	public java.lang.String getPADR() {
		return this.PADR;
	}

	public void setPADR(java.lang.String PADR) {
		this.PADR = PADR;
	}

	public java.lang.String getLanguage() {
		return this.language;
	}

	public void setLanguage(java.lang.String language) {
		this.language = language;
	}

	public int getFeedBack() {
		return this.feedBack;
	}

	public void setFeedBack(int feedBack) {
		this.feedBack = feedBack;
	}

	public Translator(java.lang.String id, java.lang.String level,
			java.lang.String ADRESS, java.lang.String PADR,
			java.lang.String language, int feedBack) {
		this.id = id;
		this.level = level;
		this.ADRESS = ADRESS;
		this.PADR = PADR;
		this.language = language;
		this.feedBack = feedBack;
	}

}